### ISSUE TITLE
notifier not working in watch mode

### ISSUE THREAD

**Issue by oluul** [Turbo87/webpack-notifier#14]
hi.
notify of the first build successful, but the second, third did not notify.

**Comment by Turbo87** [comment]
did the second/third build fail?

**Comment by oluul** [comment]
No, when the failure of the success tips

**Comment by Turbo87** [comment]
you should use the `alwaysNotify` setting if you want to see notifications for successful builds too (https://github.com/Turbo87/webpack-notifier#always-notify)
