### ISSUE TITLE
Fix npm version issues with 1.3.0/1.3.1

### ISSUE THREAD

**Issue by dmarkow** [Turbo87/webpack-notifier#15]
`npm outdated` keeps saying:

```
Package           Current  Wanted  Latest  Location
webpack-notifier    1.3.0   1.3.1   1.3.0  myapp
```

When I check https://www.npmjs.com/package/webpack-notifier it says 1.3.0 is the latest version. Listing creation times for the package shows 1.3.0 coming __after__ 1.3.1:

```
$ npm view webpack-notifier time

{ modified: '2016-02-22T13:11:25.705Z',
  created: '2015-02-12T11:40:26.317Z',
  '1.0.0': '2015-02-12T11:40:26.317Z',
  '1.0.1': '2015-02-12T21:30:56.211Z',
  '1.1.0': '2015-02-27T11:31:46.128Z',
  '1.1.1': '2015-02-27T20:09:58.777Z',
  '1.2.0': '2015-03-15T09:07:59.019Z',
  '1.2.1': '2015-04-16T07:07:11.887Z',
  '1.3.1': '2016-02-22T13:11:11.249Z',
  '1.3.0': '2016-02-22T13:11:25.705Z' }
```

It looks like the only change in 1.3.1 was to "republish to npm" but that's somehow causing the version mismatch now. It might just need a version bump  (1.3.2?) and push to npm to fix this?

**Comment by Turbo87** [comment]
since v1.4.x has been published in the meantime I'm closing this as resolved
