### ISSUE TITLE
Add optional sound effect for notifications

### ISSUE THREAD

**Issue by casprwang** [Turbo87/webpack-notifier#22]
just like [gulp-notifier](https://github.com/mikaelbr/gulp-notify#notifyoptions) does

**Comment by Turbo87** [comment]
@wangsongiam PR welcome, but I'd suggest to make it configurable as I believe many users would likely be annoyed by this

**Comment by mightym** [comment]
You can just pass ` sound: true` in the options to get the basic sound of  Notification Center or Windows Toasters.

See: https://github.com/mikaelbr/node-notifier

**Comment by Gvozd** [comment]
Documentation updated
https://github.com/Turbo87/webpack-notifier/blob/master/README.md#all-node-notifier-options
