### ISSUE TITLE
Webpack 2 support?

### ISSUE THREAD

**Issue by goldylucks** [Turbo87/webpack-notifier#24]
I c the example uses [webpack 1](https://github.com/Turbo87/webpack-notifier/blob/master/example/package.json#L9)

Is there a roadmap for webpack 2 support?

I could take a swing at it with some directions :)

**Comment by Turbo87** [comment]
@goldylucks I'm actually not using webpack anymore myself, but feel free to make this compatible

**Comment by goldylucks** [comment]
ok I might take a swing at it when I have some free time.

You want to keep the issue open in case someone else would want to implement that as well?

**Comment by bokswagen** [comment]
my team uses this for my webpack 2 builds. It works the same as webpack 1. What's your error? We're on PC's and Macs.

**Comment by goldylucks** [comment]
@bokswagen I just don't see any notification, the plugin doesn't seem to do anything.
Using ubuntu `16.4.2`

**Comment by Gvozd** [comment]
@goldylucks 
I am successfully using this plugin with webpack@4
I guess it works well with other versions too

the plugin had some problems displaying errors on some platforms, but these have been fixed
try version 1.9.0 or newer
Please reopen issue if problem persists
