### ISSUE TITLE
if it is multi-compiler configuration, how to  skip first notification

### ISSUE THREAD

**Issue by ketuzhong** [Turbo87/webpack-notifier#26]

**Comment by Gvozd** [comment]
@ketuzhong 
Tell us more about why you want this option?
Why is the current behavior inconvenient with this configuration?

I have no experience with multi-compilerconfigurations and therefore cannot appreciate the advantage of this option
Please give a minimally reproducible example (preferably in the form of a repository) that would show the inconvenience of the current behavior
