### ISSUE TITLE
Unable to make it work in my configuration webpack 5.3.0 + node 8.5.0

### ISSUE THREAD

**Issue by reficedev** [Turbo87/webpack-notifier#31]
I would like to have notification when my JS and CSS are compiled (watch and prod) but I dont manage to make it work.

Here is my webpack.config.js and package.json, which only display the test 'message' notification.

Did I miss something ?

[webpack_conf.zip](https://github.com/Turbo87/webpack-notifier/files/1320305/webpack_conf.zip)

**Comment by Gvozd** [comment]
@reficedev 
probably fixed
try version 1.9.0 or newer

reopen if problem persists
