### ISSUE TITLE
Suppress Terminal Icon (macOS)

### ISSUE THREAD

**Issue by mfour-merickson** [Turbo87/webpack-notifier#32]
I have the following configuration

```
    new WebpackNotifierPlugin({
      title: 'Webpack DIY Build Status',
      excludeWarnings: true,
      icon: path.join(__dirname, 'resources/assets/logo.png')
    }),
```

and all works as expected.  However, I am curious if it possible to suppress the small terminal icon that is part of the title (only appears when I have customized the icon property

![image](https://user-images.githubusercontent.com/31225533/31579900-72ae478a-b0f5-11e7-8fed-deca1035800a.png)

**Comment by Gvozd** [comment]
@mfour-merickson 
It looks like this is not an easy task, and requires recompilation of `terminal-notifier`

See [`node-notifier` documentation ](https://www.npmjs.com/package/node-notifier#macos-custom-icon-without-terminal-icon) for more info

I believe that this task does not belong to this package, but rather to `node-notifier`, so I close the issue
