### ISSUE TITLE
Respons with success even though it is error

### ISSUE THREAD

**Issue by hmol** [Turbo87/webpack-notifier#34]
See screenshot. Code has error, webpack compiles and finds the error. But the webpack-notifier does not display the error, only success.
![notification-error](https://user-images.githubusercontent.com/703500/33758567-081109b4-dbff-11e7-9c97-183bdf8a5416.png)

**Comment by Turbo87** [comment]
It says in your screenshot that is "Compiled successfully" :thin

**Comment by hmol** [comment]
Yes. So it is probably a webpack config thing.

**Comment by KJlmfe** [comment]
> Yes. So it is probably a webpack config thing.

I face this issue, too. How did you resolve this issue
