### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by QuentinPetel** [Turbo87/webpack-notifier#37]
Hi,

The package node-notifier (prior to 5.0.0) has a known security vulnerability due to the use of the package 'cli-usage' (prior to 0.1.7) that use the 'marked' (prior to 0.3.9) package.

    │ ├─┬ webpack-notifier@1.5.0
    │ │ ├─┬ node-notifier@4.6.1
    │ │ │ ├─┬ cli-usage@0.1.4
    │ │ │ │ ├── marked@0.3.7 (vulnerabbility prior to 0.3.9)

Consider upgrading to node-notifier @5.0.0 or overriding nested dependency version.

Quentin Pétel

**Comment by Turbo87** [comment]
https://github.com/Turbo87/webpack-notifier/blob/master/package.json#L28...

**Comment by fitztrev** [comment]
just needs a tag

**Comment by QuentinPetel** [comment]
Thank you ! 

Could we have an updated npm package too ?

**Comment by Turbo87** [comment]
Should be published to npm as v1.5.1 in a few minutes.
