### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by tjunnone** [Turbo87/webpack-notifier#38]
When webpack-notifier is used with webpack 4 (tested with 4.1.0), a deprecation warning is issued:

(node:23649) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by IgorKurkov** [comment]
`node --trace-deprecation ./node_modules/webpack/bin/webpack --bail --env dist -p` on windows helps to figure out that this plugin use `tapable` as deprecated module. 
thank you for the update!
