### ISSUE TITLE
Icon not showing (Linux/Elementary OS)

### ISSUE THREAD

**Issue by pietrofxq** [Turbo87/webpack-notifier#40]
Hello, I have a file called 'logo.png' in my webpack directory. I read the source and know that this is the default, but either not setting it in options or passing it explicit does not make the icon show in the notification. I tried with .jpg, .svg and .png with no success. I'm running Elementary OS. Is there a way to fix it?

**Comment by Gvozd** [comment]
@pietrofxq 
Please, try version 1.9.0 or newer
Does the problem recur?

With default options is showed this default icon?
https://github.com/Turbo87/webpack-notifier/blob/master/logo.png
If displayed, then try the full path to your png file - `path.join(__dirname, 'custom.png')`

if the default icon is not displayed either, please specify your version of Elementary OS

**Comment by Gvozd** [comment]
reopen in the case of repetition
