### ISSUE TITLE
No notifier when build happens inside docker container

### ISSUE THREAD

**Issue by damianobarbati** [Turbo87/webpack-notifier#41]
How can I have the notifier properly work when building webpack inside a docker container?

**Comment by Turbo87** [comment]
I don't think that's possible...

**Comment by damianobarbati** [comment]
Oh no...
Further reference: https://github.com/mikaelbr/node-notifier/issues/200

**Comment by Turbo87** [comment]
closing until mikaelbr/node-notifier#200 has a solution
