### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by Edza** [Turbo87/webpack-notifier#45]
If I use this plugin in my codebase I get the following error: 

UnhandledPromiseRejectionWarning: Error: spawn ENAMETOOLONG

at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at Object.module.exports.fileCommand (...\node-notifier\lib\utils.js:69:13)
    at WindowsToaster.notify (...\node_modules\node-notifier\notifiers\toaster.js:94:9)
    at module.exports.WebpackNotifierPlugin.compilationDone (...\node_modules\webpack-notifier\index.js:62:18)
    at args (...\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:52:19)

If I disable this plugin, the errors goes away without any problems.

I am open to contribute on this issue. Where could the problem be?

**Comment by Turbo87** [comment]
Windows has a character limit on pathnames, and apparently you're hitting that. There is nothing we can do about this here, you'd probably have to use less subfolders for your project.

**Comment by Edza** [comment]
Is there any part I could rewrite? I mean forking your repo and using some other library.

**Comment by Turbo87** [comment]
no, this is a problem of your operating system and file structure, not a problem of the code in here.

**Comment by Edza** [comment]
But why every other webpack plugin works fine? I bet they are using a different processing mechanism for paths. This is a common problem. The solution is probably not easy, but definitely doable.

I'll do the coding, if you can point me in the right direction. :)

**Comment by Edza** [comment]
I ended up changing the image src to '' and it works fine now.

**Comment by wolfingduck** [comment]
Hello,
I have the same problem:
[INFO] node:internal/errors:464
[INFO] ErrorCaptureStackTrace(err);
[INFO] ^
[INFO]
[INFO] Error: spawn ENAMETOOLONG
[INFO] at ChildProcess.spawn (node:internal/child_process:412:11)
[INFO] at spawn (node:child_process:698:9)
[INFO] at Object.execFile (node:child_process:325:17)
[INFO] at Object.module.exports.fileCommand (E:\jhispster\my_proj\node_modules\webpack-notifier\node_modules\node-notifier\lib\utils.js:76:13)
[INFO] at E:\jhispster\my_proj\node_modules\webpack-notifier\node_modules\node-notifier\notifiers\toaster.js:145:11
[INFO] at runMicrotasks ()
[INFO] at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[INFO] errno: -4064,
[INFO] code: 'ENAMETOOLONG',
[INFO] syscall: 'spawn'
[INFO] }
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -----------------------------

Anyone have any ideas on this?
