### ISSUE TITLE
[Question] How to change the host and port which webpack-notifier calls

### ISSUE THREAD

**Issue by neorganic** [Turbo87/webpack-notifier#47]
So webpack-notifier uses node-notifier as a core package and node-notifier has a default host ip and default port. I am trying to make webpack-notifier to work when it's used inside a docker container. I am actually close but need to solve this key Q.

**Comment by neorganic** [comment]
case closed. Found a way how to listen for webpack-notifier events and from here can do whatever is needed.

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/event-hooks.md

**Comment by pablocarreraest** [comment]
@neorganic hi is posible to give and example of this I'm using nodejs not laravel
