### ISSUE TITLE
Notifier Doesn't Always Show

### ISSUE THREAD

**Issue by crazyjat** [Turbo87/webpack-notifier#50]
Setup:
webpack 3.12.0
npm 6.4.1
node 8.9.4
Visual Studio 2015 Update 3
WebPack Task Runner 1.5.94
Windows 10

I have no idea how to reliably reproduce this, but sometimes the notification popup never shows up after webpack finishes a build. Once it stops showing up, the only way to get it to show up again is to restart Visual Studio, and sometimes that doesn't even work.

Anyone else experience this issue?

Know how to fix it?

**Comment by thasmo** [comment]
Did you inspect the available options for this plugin and did you ensure it's not related to those?

**Comment by Gvozd** [comment]
@crazyjat 
If you use yarn, try this temp workaround
https://github.com/Turbo87/webpack-notifier/pull/56#issuecomment-555454262

he helps me
will he help you?

**Comment by Gvozd** [comment]
@crazyjat 
probably fixed
try version 1.9.0 or newer
