### ISSUE TITLE
Notifications not showing up on Windows 10

### ISSUE THREAD

**Issue by marveloo** [Turbo87/webpack-notifier#57]
After updating to Windows 10 1903 or newer version, notifications stopped popping up. Actually the first notification shows up as expected but all subsequent notifications keep getting queued (or something) and they show up all at once in the notification area after a machine reboot.

It seems that updating node-notifier to v6 solves the issue. See [here](https://github.com/RoccoC/webpack-build-notifier/issues/43#issuecomment-542451966).

**Comment by marveloo** [comment]
#56

**Comment by marveloo** [comment]
It looks there is a pull request for this already #56

**Comment by Gvozd** [comment]
@marveloo try version 1.9.0 or newer
Please reopen issue if problem persists
