### ISSUE TITLE
Too long error message might crash build

### ISSUE THREAD

**Issue by Shastel** [Turbo87/webpack-notifier#58]
If for some reason message will exceed `ARG_MAX`, it will crash the whole build on macOS with `E2BIG` error.

**Comment by Gvozd** [comment]
@Shastel 
Please, try version 1.9.0 or newer
Does the problem recur?

If repeated, please give a minimally reproducible example (preferably in the form of a repository) that reproduces the problems

**Comment by Gvozd** [comment]
reopen in the case of repetition
