### ISSUE TITLE
Remove SnoreToast message from notification in Windows 10

### ISSUE THREAD

**Issue by Nothing-Works** [Turbo87/webpack-notifier#64]
Snoretoast is always added to the start menu as a shortcut and creates a registry key which is very annoying.
![Untitled](https://user-images.githubusercontent.com/18606648/101856604-807c6280-3bca-11eb-91f2-5e6a76367bef.png)
This is an issue from [node-notifier](https://github.com/mikaelbr/node-notifier/issues/154)

To fix this we need to pass `appID`, can we do this in this library?

I am not using `webpack-notifier` directly, I am using [laravel-mix](https://github.com/JeffreyWay/laravel-mix) and it uses this library for notification. Here is the [issue](https://github.com/JeffreyWay/laravel-mix/issues/2671). What's the easiest thing to do?

**Update:** after reading the source code seems like that I can just past the object into `WebpackNotifierPlugin` like this?

```js
WebpackNotifierPlugin({
   appID: 'fooBar'
});
```
Will this do the right thing?

**Comment by Gvozd** [comment]
Yes, such transfer as a parameter is allowed
You only need to write `new WebpackNotifierPlugin` of course

Covered with tests

I also planned to add an alternative way of setting options in the future - #65 
```
new WebpackNotifierPlugin ({
  notifier: 'NotificationCenter',// or constructor - require('node-notifier').NotificationCenter
  notifierOptions: {
    withFallback: false,
    customPath: undefined
  },
  notifyOptions: {
    appId: 'com.squirrel.your.app'
  }
});
```

**Comment by Nothing-Works** [comment]
@Gvozd I like the solution you proposed #65, it's very flexible, clear and I know what's happening also feels more like the `node-notifier` native api.

**Comment by Gvozd** [comment]
@Nothing-Works, Wonderful!)

In the meantime, this solution is not ready, you can use the method you already found
I will maintain backward compatibility with it throughout the current major release.
