### ISSUE TITLE
TypeScript error -  Module '"webpack"' has no exported member 'Plugin'.

### ISSUE THREAD

**Issue by marchaos** [Turbo87/webpack-notifier#73]
Getting this error when using webpack version `5.58.2`, although it is probably present on versions before this. I think you need to update the types to a later version.

**Comment by s00d** [comment]
hello. fix [#74](https://github.com/Turbo87/webpack-notifier/pull/74) please update

**Comment by Gvozd** [comment]
@marchaos @s00d 
fix available at v1.15.0
reopen if there are problems
